//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dathang
    {
        public string Hoadon_id { get; set; }
        public string sanpham_id { get; set; }
        public string Khachhang_name { get; set; }
        public string Diachi { get; set; }
        public string NV_id { get; set; }
        public Nullable<System.DateTime> ngaydathang { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
