//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang
    {
        public string Hoadon_id { get; set; }
        public string sanpham_id { get; set; }
        public string Khachhang_id { get; set; }
        public string Khachhang_name { get; set; }
        public string sanpham_name { get; set; }
        public int soluong { get; set; }
        public Nullable<int> giaban { get; set; }
        public Nullable<int> tongtien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
