//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.Dathangs = new HashSet<Dathang>();
            this.Donhangs = new HashSet<Donhang>();
        }
    
        public string sanpham_id { get; set; }
        public string Loaisp_id { get; set; }
        public string sanpham_name { get; set; }
        public Nullable<int> gia { get; set; }
        public string Nhacungcap_id { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dathang> Dathangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donhang> Donhangs { get; set; }
        public virtual LoaiSp LoaiSp { get; set; }
        public virtual Nhacungcap Nhacungcap { get; set; }
    }
}
