//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string Mabaiviet { get; set; }
        public string Tieude { get; set; }
        public string Noidung { get; set; }
        public string Anh { get; set; }
    }
}
